# Generated by Django 4.2.3 on 2023-11-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_username_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='owner_name',
        ),
        migrations.DeleteModel(
            name='bid',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='listing',
        ),
    ]
