# Generated by Django 4.2.3 on 2023-11-11 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_comment_topic_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=26)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('duration', models.DurationField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='auctions.category')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ManyToManyField(related_name='comments', to='auctions.listing')),
                ('username', models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField()),
                ('bidder', models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('item', models.ManyToManyField(related_name='bids', to='auctions.listing')),
            ],
        ),
    ]
