# Generated by Django 4.2.3 on 2023-11-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_listing_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.DeleteModel(
            name='bid',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
