# Generated by Django 4.2.3 on 2023-11-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name_plural': 'bid'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'category'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comment'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'listings'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'user'},
        ),
    ]
