# Generated by Django 4.2.3 on 2023-11-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='duration',
        ),
    ]
