# Generated by Django 4.2.3 on 2023-11-12 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
