# Generated by Django 4.2.3 on 2023-11-23 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
