# Generated by Django 4.2.3 on 2023-11-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comment_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='', max_length=1000, null=True),
        ),
    ]
